/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as PracticeIdRouteImport } from './routes/practice.$id'
import { Route as DayDayRouteImport } from './routes/day.$day'
import { Route as ShellSupportRouteImport } from './routes/_shell.support'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellResourcesRouteImport } from './routes/_shell.resources'
import { Route as ShellPracticesRouteImport } from './routes/_shell.practices'
import { Route as ShellJourneyRouteImport } from './routes/_shell.journey'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const PracticeIdRoute = PracticeIdRouteImport.update({
  id: '/practice/$id',
  path: '/practice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DayDayRoute = DayDayRouteImport.update({
  id: '/day/$day',
  path: '/day/$day',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellSupportRoute = ShellSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellResourcesRoute = ShellResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPracticesRoute = ShellPracticesRouteImport.update({
  id: '/practices',
  path: '/practices',
  getParentRoute: () => ShellRoute,
} as any)
const ShellJourneyRoute = ShellJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/journey': typeof ShellJourneyRoute
  '/practices': typeof ShellPracticesRoute
  '/resources': typeof ShellResourcesRoute
  '/settings': typeof ShellSettingsRoute
  '/support': typeof ShellSupportRoute
  '/day/$day': typeof DayDayRoute
  '/practice/$id': typeof PracticeIdRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/journey': typeof ShellJourneyRoute
  '/practices': typeof ShellPracticesRoute
  '/resources': typeof ShellResourcesRoute
  '/settings': typeof ShellSettingsRoute
  '/support': typeof ShellSupportRoute
  '/day/$day': typeof DayDayRoute
  '/practice/$id': typeof PracticeIdRoute
  '/': typeof ShellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_shell/journey': typeof ShellJourneyRoute
  '/_shell/practices': typeof ShellPracticesRoute
  '/_shell/resources': typeof ShellResourcesRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/support': typeof ShellSupportRoute
  '/day/$day': typeof DayDayRoute
  '/practice/$id': typeof PracticeIdRoute
  '/_shell/': typeof ShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/journey'
    | '/practices'
    | '/resources'
    | '/settings'
    | '/support'
    | '/day/$day'
    | '/practice/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/journey'
    | '/practices'
    | '/resources'
    | '/settings'
    | '/support'
    | '/day/$day'
    | '/practice/$id'
    | '/'
  id:
    | '__root__'
    | '/_shell'
    | '/onboarding'
    | '/_shell/journey'
    | '/_shell/practices'
    | '/_shell/resources'
    | '/_shell/settings'
    | '/_shell/support'
    | '/day/$day'
    | '/practice/$id'
    | '/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  DayDayRoute: typeof DayDayRoute
  PracticeIdRoute: typeof PracticeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/practice/$id': {
      id: '/practice/$id'
      path: '/practice/$id'
      fullPath: '/practice/$id'
      preLoaderRoute: typeof PracticeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/$day': {
      id: '/day/$day'
      path: '/day/$day'
      fullPath: '/day/$day'
      preLoaderRoute: typeof DayDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/support': {
      id: '/_shell/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof ShellSupportRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/resources': {
      id: '/_shell/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ShellResourcesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/practices': {
      id: '/_shell/practices'
      path: '/practices'
      fullPath: '/practices'
      preLoaderRoute: typeof ShellPracticesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/journey': {
      id: '/_shell/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof ShellJourneyRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellJourneyRoute: typeof ShellJourneyRoute
  ShellPracticesRoute: typeof ShellPracticesRoute
  ShellResourcesRoute: typeof ShellResourcesRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellSupportRoute: typeof ShellSupportRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellJourneyRoute: ShellJourneyRoute,
  ShellPracticesRoute: ShellPracticesRoute,
  ShellResourcesRoute: ShellResourcesRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellSupportRoute: ShellSupportRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  DayDayRoute: DayDayRoute,
  PracticeIdRoute: PracticeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
