/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PilotFeedbackRouteImport } from './routes/pilot-feedback'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ImportantInformationRouteImport } from './routes/important-information'
import { Route as ContactSupportRouteImport } from './routes/contact-support'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as SessionWeek01RouteImport } from './routes/session.week-01'
import { Route as PracticeIdRouteImport } from './routes/practice.$id'
import { Route as DayDayRouteImport } from './routes/day.$day'
import { Route as ShellSupportRouteImport } from './routes/_shell.support'
import { Route as ShellShiftedRouteImport } from './routes/_shell.shifted'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellResourcesRouteImport } from './routes/_shell.resources'
import { Route as ShellPracticesRouteImport } from './routes/_shell.practices'
import { Route as ShellJourneyRouteImport } from './routes/_shell.journey'
import { Route as DayDayReflectionRouteImport } from './routes/day.$day.reflection'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotFeedbackRoute = PilotFeedbackRouteImport.update({
  id: '/pilot-feedback',
  path: '/pilot-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportantInformationRoute = ImportantInformationRouteImport.update({
  id: '/important-information',
  path: '/important-information',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactSupportRoute = ContactSupportRouteImport.update({
  id: '/contact-support',
  path: '/contact-support',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const SessionWeek01Route = SessionWeek01RouteImport.update({
  id: '/session/week-01',
  path: '/session/week-01',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIdRoute = PracticeIdRouteImport.update({
  id: '/practice/$id',
  path: '/practice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DayDayRoute = DayDayRouteImport.update({
  id: '/day/$day',
  path: '/day/$day',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellSupportRoute = ShellSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ShellRoute,
} as any)
const ShellShiftedRoute = ShellShiftedRouteImport.update({
  id: '/shifted',
  path: '/shifted',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellResourcesRoute = ShellResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPracticesRoute = ShellPracticesRouteImport.update({
  id: '/practices',
  path: '/practices',
  getParentRoute: () => ShellRoute,
} as any)
const ShellJourneyRoute = ShellJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => ShellRoute,
} as any)
const DayDayReflectionRoute = DayDayReflectionRouteImport.update({
  id: '/reflection',
  path: '/reflection',
  getParentRoute: () => DayDayRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/contact-support': typeof ContactSupportRoute
  '/important-information': typeof ImportantInformationRoute
  '/onboarding': typeof OnboardingRoute
  '/pilot-feedback': typeof PilotFeedbackRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/journey': typeof ShellJourneyRoute
  '/practices': typeof ShellPracticesRoute
  '/resources': typeof ShellResourcesRoute
  '/settings': typeof ShellSettingsRoute
  '/shifted': typeof ShellShiftedRoute
  '/support': typeof ShellSupportRoute
  '/day/$day': typeof DayDayRouteWithChildren
  '/practice/$id': typeof PracticeIdRoute
  '/session/week-01': typeof SessionWeek01Route
  '/day/$day/reflection': typeof DayDayReflectionRoute
}
export interface FileRoutesByTo {
  '/contact-support': typeof ContactSupportRoute
  '/important-information': typeof ImportantInformationRoute
  '/onboarding': typeof OnboardingRoute
  '/pilot-feedback': typeof PilotFeedbackRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/journey': typeof ShellJourneyRoute
  '/practices': typeof ShellPracticesRoute
  '/resources': typeof ShellResourcesRoute
  '/settings': typeof ShellSettingsRoute
  '/shifted': typeof ShellShiftedRoute
  '/support': typeof ShellSupportRoute
  '/day/$day': typeof DayDayRouteWithChildren
  '/practice/$id': typeof PracticeIdRoute
  '/session/week-01': typeof SessionWeek01Route
  '/': typeof ShellIndexRoute
  '/day/$day/reflection': typeof DayDayReflectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/contact-support': typeof ContactSupportRoute
  '/important-information': typeof ImportantInformationRoute
  '/onboarding': typeof OnboardingRoute
  '/pilot-feedback': typeof PilotFeedbackRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_shell/journey': typeof ShellJourneyRoute
  '/_shell/practices': typeof ShellPracticesRoute
  '/_shell/resources': typeof ShellResourcesRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/shifted': typeof ShellShiftedRoute
  '/_shell/support': typeof ShellSupportRoute
  '/day/$day': typeof DayDayRouteWithChildren
  '/practice/$id': typeof PracticeIdRoute
  '/session/week-01': typeof SessionWeek01Route
  '/_shell/': typeof ShellIndexRoute
  '/day/$day/reflection': typeof DayDayReflectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact-support'
    | '/important-information'
    | '/onboarding'
    | '/pilot-feedback'
    | '/privacy'
    | '/terms'
    | '/journey'
    | '/practices'
    | '/resources'
    | '/settings'
    | '/shifted'
    | '/support'
    | '/day/$day'
    | '/practice/$id'
    | '/session/week-01'
    | '/day/$day/reflection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contact-support'
    | '/important-information'
    | '/onboarding'
    | '/pilot-feedback'
    | '/privacy'
    | '/terms'
    | '/journey'
    | '/practices'
    | '/resources'
    | '/settings'
    | '/shifted'
    | '/support'
    | '/day/$day'
    | '/practice/$id'
    | '/session/week-01'
    | '/'
    | '/day/$day/reflection'
  id:
    | '__root__'
    | '/_shell'
    | '/contact-support'
    | '/important-information'
    | '/onboarding'
    | '/pilot-feedback'
    | '/privacy'
    | '/terms'
    | '/_shell/journey'
    | '/_shell/practices'
    | '/_shell/resources'
    | '/_shell/settings'
    | '/_shell/shifted'
    | '/_shell/support'
    | '/day/$day'
    | '/practice/$id'
    | '/session/week-01'
    | '/_shell/'
    | '/day/$day/reflection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  ContactSupportRoute: typeof ContactSupportRoute
  ImportantInformationRoute: typeof ImportantInformationRoute
  OnboardingRoute: typeof OnboardingRoute
  PilotFeedbackRoute: typeof PilotFeedbackRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  DayDayRoute: typeof DayDayRouteWithChildren
  PracticeIdRoute: typeof PracticeIdRoute
  SessionWeek01Route: typeof SessionWeek01Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot-feedback': {
      id: '/pilot-feedback'
      path: '/pilot-feedback'
      fullPath: '/pilot-feedback'
      preLoaderRoute: typeof PilotFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/important-information': {
      id: '/important-information'
      path: '/important-information'
      fullPath: '/important-information'
      preLoaderRoute: typeof ImportantInformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-support': {
      id: '/contact-support'
      path: '/contact-support'
      fullPath: '/contact-support'
      preLoaderRoute: typeof ContactSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/session/week-01': {
      id: '/session/week-01'
      path: '/session/week-01'
      fullPath: '/session/week-01'
      preLoaderRoute: typeof SessionWeek01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$id': {
      id: '/practice/$id'
      path: '/practice/$id'
      fullPath: '/practice/$id'
      preLoaderRoute: typeof PracticeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/$day': {
      id: '/day/$day'
      path: '/day/$day'
      fullPath: '/day/$day'
      preLoaderRoute: typeof DayDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/support': {
      id: '/_shell/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof ShellSupportRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/shifted': {
      id: '/_shell/shifted'
      path: '/shifted'
      fullPath: '/shifted'
      preLoaderRoute: typeof ShellShiftedRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/resources': {
      id: '/_shell/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ShellResourcesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/practices': {
      id: '/_shell/practices'
      path: '/practices'
      fullPath: '/practices'
      preLoaderRoute: typeof ShellPracticesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/journey': {
      id: '/_shell/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof ShellJourneyRouteImport
      parentRoute: typeof ShellRoute
    }
    '/day/$day/reflection': {
      id: '/day/$day/reflection'
      path: '/reflection'
      fullPath: '/day/$day/reflection'
      preLoaderRoute: typeof DayDayReflectionRouteImport
      parentRoute: typeof DayDayRoute
    }
  }
}

interface ShellRouteChildren {
  ShellJourneyRoute: typeof ShellJourneyRoute
  ShellPracticesRoute: typeof ShellPracticesRoute
  ShellResourcesRoute: typeof ShellResourcesRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellShiftedRoute: typeof ShellShiftedRoute
  ShellSupportRoute: typeof ShellSupportRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellJourneyRoute: ShellJourneyRoute,
  ShellPracticesRoute: ShellPracticesRoute,
  ShellResourcesRoute: ShellResourcesRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellShiftedRoute: ShellShiftedRoute,
  ShellSupportRoute: ShellSupportRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface DayDayRouteChildren {
  DayDayReflectionRoute: typeof DayDayReflectionRoute
}

const DayDayRouteChildren: DayDayRouteChildren = {
  DayDayReflectionRoute: DayDayReflectionRoute,
}

const DayDayRouteWithChildren =
  DayDayRoute._addFileChildren(DayDayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  ContactSupportRoute: ContactSupportRoute,
  ImportantInformationRoute: ImportantInformationRoute,
  OnboardingRoute: OnboardingRoute,
  PilotFeedbackRoute: PilotFeedbackRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  DayDayRoute: DayDayRouteWithChildren,
  PracticeIdRoute: PracticeIdRoute,
  SessionWeek01Route: SessionWeek01Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
