// Customer-readiness Pass A regression tests: preference sanitization,
// fail-closed dormant AI, completed-day revisit resume, closing containment,
// the Day 1 spiritual invitation, and hidden legacy surfaces.

import { describe, expect, it } from "vitest";

import { sanitizePrefs, PREF_DEFAULTS } from "@/lib/prefs";
import { hasMeaningfulProgress, type JourneyProgress } from "@/lib/journey/progress";
import { LIVE_AI_ENABLED_DEFAULT } from "@/lib/ai/compute";

function progress(patch: Partial<JourneyProgress>): JourneyProgress {
  return {
    version: 3,
    answers: {},
    reflections: {},
    completedDays: [],
    locator: null,
    ...patch,
  } as JourneyProgress;
}

describe("spiritual preference sanitization is fail-safe", () => {
  it("only a literal true enables the Christian path", () => {
    for (const value of ["true", "1", 1, {}, [], "yes", null, undefined]) {
      expect(sanitizePrefs({ showSpiritual: value }).showSpiritual).toBe(false);
    }
    expect(sanitizePrefs({ showSpiritual: true }).showSpiritual).toBe(true);
  });

  it("a corrupt or hostile store falls back to the opt-in defaults", () => {
    for (const raw of [null, undefined, 7, "prefs", [1, 2, 3]]) {
      expect(sanitizePrefs(raw)).toEqual(PREF_DEFAULTS);
    }
  });

  it("discards malformed visited days and malformed acceptance", () => {
    const out = sanitizePrefs({
      visitedDays: [1, 1, 2.5, -3, "4", null, 3],
      legalAcceptance: { version: "", acceptedAt: "x" },
    });
    // 2.5 is not whole, "4" is not a number, -3 is out of range: all discarded.
    expect(out.visitedDays).toEqual([1, 3]);

    expect(out.legalAcceptance).toBeUndefined();
  });
});

describe("dormant AI fails closed", () => {
  it("defaults to off, so nothing can be generated by accident", () => {
    expect(LIVE_AI_ENABLED_DEFAULT).toBe(false);
  });
});

describe("completed-day revisit resume", () => {
  it("returns to an exact mid-day place inside a finished day", () => {
    expect(
      hasMeaningfulProgress(
        progress({
          completedDays: ["day-02"],
          locator: { dayId: "day-02", step: "listen", index: 2 },
        }),
      ),
    ).toBe(true);
  });

  it("does not offer a resume when a finished day sits on its own close", () => {
    expect(
      hasMeaningfulProgress(
        progress({
          completedDays: ["day-02"],
          locator: { dayId: "day-02", step: "close", index: 0 },
        }),
      ),
    ).toBe(false);
  });

  it("still ignores an untouched opening screen", () => {
    expect(
      hasMeaningfulProgress(
        progress({ locator: { dayId: "day-01", step: "arrive", index: 0 } }),
      ),
    ).toBe(false);
  });
});

describe("daily closing supports containment", () => {
  it("names one day at a time and never urges continuing now", async () => {
    const { CLOSE_CONTAINMENT_NOTE } = await import("@/routes/day.$day");
    expect(CLOSE_CONTAINMENT_NOTE).toContain("One day at a time");
    expect(CLOSE_CONTAINMENT_NOTE).toMatch(/no need to continue now/i);
  });

  it("keeps the Day 1 spiritual mention optional, findable and unpressured", async () => {
    const { SPIRITUAL_INVITATION_TEXT, SPIRITUAL_INVITATION_LINK_LABEL } =
      await import("@/routes/day.$day");
    expect(SPIRITUAL_INVITATION_TEXT).toMatch(/complete on its own/i);
    expect(SPIRITUAL_INVITATION_TEXT).toMatch(/optional/i);
    expect(SPIRITUAL_INVITATION_TEXT).toMatch(/Settings/);
    expect(SPIRITUAL_INVITATION_TEXT).not.toMatch(/should|must|recommend/i);
    expect(SPIRITUAL_INVITATION_LINK_LABEL).toBe("Open Settings");
  });
});

describe("unfinished legacy surfaces are not reachable", () => {
  it("resolves the retired practices and resources paths to the journey home", async () => {
    for (const mod of [
      "@/routes/_shell.practices",
      "@/routes/_shell.resources",
      "@/routes/practice.$id",
    ]) {
      const loaded = (await import(mod)) as { Route: { options?: unknown } };
      expect(loaded.Route).toBeTruthy();
    }
  });
});
