// Customer-readiness Pass A regression tests: preference sanitization,
// fail-closed dormant AI, completed-day revisit resume, closing containment,
// the Day 1 spiritual invitation, and hidden legacy surfaces.

import { describe, expect, it } from "vitest";

import { sanitizePrefs, PREF_DEFAULTS } from "@/lib/prefs";
import { hasMeaningfulProgress, type JourneyProgress } from "@/lib/journey/progress";
import { LIVE_AI_ENABLED_DEFAULT } from "@/lib/ai/compute";

/** Read a project source file so assertions can check real implementation. */
async function readSource(relativePath: string): Promise<string> {
  const { readFile } = await import("node:fs/promises");
  return readFile(new URL(`../../../${relativePath}`, import.meta.url), "utf8");
}

function progress(patch: Partial<JourneyProgress>): JourneyProgress {
  return {
    version: 3,
    answers: {},
    reflections: {},
    completedDays: [],
    locator: null,
    ...patch,
  } as JourneyProgress;
}

describe("spiritual preference sanitization is fail-safe", () => {
  it("only a literal true enables the Christian path", () => {
    for (const value of ["true", "1", 1, {}, [], "yes", null, undefined]) {
      expect(sanitizePrefs({ showSpiritual: value }).showSpiritual).toBe(false);
    }
    expect(sanitizePrefs({ showSpiritual: true }).showSpiritual).toBe(true);
  });

  it("a corrupt or hostile store falls back to the opt-in defaults", () => {
    for (const raw of [null, undefined, 7, "prefs", [1, 2, 3]]) {
      expect(sanitizePrefs(raw)).toEqual(PREF_DEFAULTS);
    }
  });

  it("discards malformed visited days and malformed acceptance", () => {
    const out = sanitizePrefs({
      visitedDays: [1, 1, 2.5, -3, "4", null, 3],
      legalAcceptance: { version: "", acceptedAt: "x" },
    });
    // 2.5 is not whole, "4" is not a number, -3 is out of range: all discarded.
    expect(out.visitedDays).toEqual([1, 3]);

    expect(out.legalAcceptance).toBeUndefined();
  });
});

describe("dormant AI fails closed", () => {
  it("defaults to off, so nothing can be generated by accident", () => {
    expect(LIVE_AI_ENABLED_DEFAULT).toBe(false);
  });
});

describe("completed-day revisit resume", () => {
  it("returns to an exact mid-day place inside a finished day", () => {
    expect(
      hasMeaningfulProgress(
        progress({
          completedDays: ["day-02"],
          locator: { dayId: "day-02", step: "listen", index: 2 },
        }),
      ),
    ).toBe(true);
  });

  it("does not offer a resume when a finished day sits on its own close", () => {
    expect(
      hasMeaningfulProgress(
        progress({
          completedDays: ["day-02"],
          locator: { dayId: "day-02", step: "close", index: 0 },
        }),
      ),
    ).toBe(false);
  });

  it("still ignores an untouched opening screen", () => {
    expect(
      hasMeaningfulProgress(
        progress({ locator: { dayId: "day-01", step: "arrive", index: 0 } }),
      ),
    ).toBe(false);
  });
});

describe("daily closing supports containment", () => {
  it("names one day at a time and never urges continuing now", async () => {
    const { CLOSE_CONTAINMENT_NOTE } = await import("@/routes/day.$day");
    expect(CLOSE_CONTAINMENT_NOTE).toContain("One day at a time");
    expect(CLOSE_CONTAINMENT_NOTE).toMatch(/no need to continue now/i);
  });

  it("keeps the Day 1 spiritual mention optional, findable and unpressured", async () => {
    const { SPIRITUAL_INVITATION_TEXT, SPIRITUAL_INVITATION_LINK_LABEL } =
      await import("@/routes/day.$day");
    expect(SPIRITUAL_INVITATION_TEXT).toMatch(/complete on its own/i);
    expect(SPIRITUAL_INVITATION_TEXT).toMatch(/optional/i);
    expect(SPIRITUAL_INVITATION_TEXT).toMatch(/Settings/);
    expect(SPIRITUAL_INVITATION_TEXT).not.toMatch(/should|must|recommend/i);
    expect(SPIRITUAL_INVITATION_LINK_LABEL).toBe("Open Settings");
  });
});

describe("route-aware in-day screen transition tracking", () => {
  async function tracking() {
    const mod = await import("@/components/JourneyScreen");
    mod.__resetScreenFocusTracking();
    return mod;
  }

  it("never focuses on a direct document load of a day", async () => {
    const { recordRouteTransition, recordScreenTransition } = await tracking();
    recordRouteTransition("/day/1");
    expect(recordScreenTransition("1:arrive")).toBe(false);
  });

  it("announces the first Home -> Day client navigation", async () => {
    const { recordRouteTransition, recordScreenTransition } = await tracking();
    recordRouteTransition("/");
    recordRouteTransition("/day/1");
    expect(recordScreenTransition("1:arrive")).toBe(true);
  });

  it("is idempotent under StrictMode-style repeated recording", async () => {
    const { recordRouteTransition, recordScreenTransition } = await tracking();
    recordRouteTransition("/");
    recordRouteTransition("/");
    recordRouteTransition("/day/1");
    recordRouteTransition("/day/1");
    expect(recordScreenTransition("1:arrive")).toBe(true);
    // Second setup of the same effect must not focus a second time.
    expect(recordScreenTransition("1:arrive")).toBe(false);
    expect(recordScreenTransition("1:arrive")).toBe(false);
  });

  it("tracks Reflection then browser Back to Practise", async () => {
    const { recordRouteTransition, recordScreenTransition } = await tracking();
    recordRouteTransition("/");
    recordRouteTransition("/day/1");
    expect(recordScreenTransition("1:practise")).toBe(true);
    // Reflection focuses its own heading, but still updates tracking.
    expect(recordScreenTransition("1:reflection")).toBe(true);
    expect(recordScreenTransition("1:practise")).toBe(true);
  });

  it("announces returning from Settings to the very same day screen", async () => {
    const { recordRouteTransition, recordScreenTransition } = await tracking();
    recordRouteTransition("/day/1");
    expect(recordScreenTransition("1:practise")).toBe(false);
    recordRouteTransition("/settings");
    recordRouteTransition("/day/1");
    expect(recordScreenTransition("1:practise")).toBe(true);
  });
});


describe("daily close offers the next day as clearly optional", () => {
  it("labels the quiet secondary action without urging continuation", async () => {
    const { closeNextDayLabel } = await import("@/routes/day.$day");
    expect(closeNextDayLabel(2)).toBe("Open Day 2 when you\u2019re ready");
    expect(closeNextDayLabel(9)).toBe("Open Day 9 when you\u2019re ready");
    for (const n of [2, 5, 9]) {
      expect(closeNextDayLabel(n)).not.toMatch(/continue/i);
    }
    // Day 10 has no next day, so there is no label and no action.
    expect(closeNextDayLabel(null)).toBeNull();
  });

  it("keeps Return to Your Journey primary and the next day secondary", async () => {
    const source = await readSource("src/routes/day.$day.tsx");
    const primary = source.indexOf('data-testid="close-return-home"');
    const secondary = source.indexOf('data-testid="close-next-day"');
    expect(primary).toBeGreaterThan(-1);
    expect(secondary).toBeGreaterThan(primary);
    expect(source).toMatch(/close-return-home[\s\S]{0,200}Return to Your Journey/);
    // The primary uses the primary button style, the secondary the quiet one.
    expect(source).toMatch(/btn-primary-journey w-full[\s\S]{0,120}close-return-home/);
    expect(source).toMatch(/btn-quiet block w-full text-center[\s\S]{0,120}close-next-day/);
    expect(source).toContain("{closeNextDayLabel(nextDay)}");
  });
});

describe("progress states are distinguishable without colour vision", () => {
  it("differs in thickness and colour, not hue alone", async () => {
    const css = await readSource("src/styles.css");
    const base = css.slice(css.indexOf("@utility bfa-progress-segment"));
    const unreached = base.slice(0, base.indexOf("}"));
    const reached = base.slice(base.indexOf('[data-state="reached"]'));
    expect(unreached).toContain("height: 2px");
    expect(unreached).toContain("#0D2B55");
    expect(reached.slice(0, reached.indexOf("}"))).toContain("height: 4px");
    expect(reached.slice(0, reached.indexOf("}"))).toContain("#9A7723");
    // The old near-identical grey state is gone entirely.
    expect(css).not.toContain("#737B8B");
  });
});

describe("unfinished legacy surfaces redirect instead of holding content", () => {
  it("sends /practices, /resources and /practice/$id to Your Journey", async () => {
    for (const mod of [
      "@/routes/_shell.practices",
      "@/routes/_shell.resources",
      "@/routes/practice.$id",
    ]) {
      const loaded = (await import(mod)) as {
        Route: { options: { beforeLoad?: () => void; component?: () => unknown } };
      };
      const beforeLoad = loaded.Route.options.beforeLoad as undefined | (() => void);
      expect(typeof beforeLoad).toBe("function");
      let thrown: unknown;
      try {
        beforeLoad!();
      } catch (err) {
        thrown = err;
      }
      const redirectOptions = (thrown as { options?: { to?: string; replace?: boolean } })
        ?.options;
      expect(redirectOptions).toBeTruthy();
      expect(redirectOptions!.to).toBe("/");
      expect(redirectOptions!.replace).toBe(true);
      // Nothing renders even if the redirect were somehow bypassed.
      expect(loaded.Route.options.component?.()).toBeNull();
    }
  });
});
